version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: hugomachado93/reverseproxy:v1
  backend_user:
    build:
      context: ../../udagram-api-user
    image: hugomachado93/udagram-api-user:v1
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: hugomachado93/udagram-api-feed:v1
  frontend:
    build:
      context: ../../udagram-frontend
    image: hugomachado93/udagram-frontend:v1
